<?php

namespace Drupal\blazy_layout\Hook;

use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;
use Drupal\blazy_layout\BlazyLayoutDefault;

/**
 * Hook implementations for theme.
 *
 * @todo add #[Hook] attribute, and change them to instance class for D11.
 */
class ThemeHooks {

  /**
   * Implements hook_theme().   */
  public static function theme() {
    return [
      'block__blazy' => [
        'base hook' => 'block',
      ],
      'field__blazy' => [
        'base hook' => 'field',
      ],
      'layout__blazy' => [
        'base hook' => 'layout',
      ],
    ];
  }

  /**
   * Overrides variables for layout.html.twig templates.
   *
   * {@inheritdoc}   */
  public static function preprocessLayout(array &$variables) {
    /** @var array<string, mixed> $attributes */
    $attributes = &$variables['attributes'];

    /** @var array<string, mixed> $settings */
    $settings = &$variables['settings'];

    /** @var array<string, mixed> $content */
    $content = $variables['content'];
    $namespace = $content['#namespace'] ?? 'x';

    if ($namespace != 'blazy') {
      return;
    }

    /** @var \Drupal\blazy\BlazySettings $blazies */
    $blazies = $settings['blazies'];
    $wrappers = $content['#wrapper_attributes'] ?? [];
    $variables['wrapper_attributes'] = new Attribute($wrappers);
    $in_preview = $variables['in_preview'];
    $count = $settings['count'] = (int) $settings['count'];
    $settings['background'] = $background = $in_preview ||
    !empty($settings['background']) ||
    !empty($content['bg']);

    $style = $settings['style'] ?? '';

    self::regionAttributes($variables, 'bg');

    // Phpstan requires assurance.
    // @todo recheck $variables = is_array($variables) ? $variables : [];.
    if ($theme = \Drupal::theme()->getActiveTheme()->getName()) {
      $attributes['class'][] = 'b-theme-' . str_replace('_', '-', $theme);
    }

    if ($in_preview) {
      if ($id = $settings['id'] ?? NULL) {
        $variables['wrapper_attributes']['data-b-id'] = $id;
      }

      $attributes['class'][] = 'b-layout--preview';
      if (is_array($variables['region_attributes'])) {
        $variables['region_attributes']['bg']['title'] = t('Background');
        $variables['region_attributes']['bg']['data-b-h'] = 'xs';
      }
    }

    if ($background) {
      $variables['region_attributes']['bg']['data-b-w'] = $style == 'nativegrid'
      ? 12
      : 100;

      if (!empty($settings['remove_bg'])) {
        $settings['background'] = FALSE;
      }
    }

    // Cleanup unused regions.
    self::cleanupRegions($variables, $count);

    // Phpstan requires assurance.
    // @todo recheck $variables = is_array($variables) ? $variables : [];.
    // Create an attributes variable for each region.
    $region_settings = $settings['regions'];
    if ($regions = $blazies->get('grid.items', [])) {
      foreach (range(1, $count) as $delta => $value) {
        $name = BlazyLayoutDefault::regionId($delta);

        // Cleanup unwanted block attributes from builtin Media background.
        self::cleanupBlockAttributes($variables, $name);

        // Core region attributes depend on content[region], hence enforced.
        self::regionAttributes($variables, $name);

        // Phpstan requires assurance.
        // @todo recheck $variables = is_array($variables) ? $variables : [];
        // Add browser title tooltip over regions.
        if ($in_preview && $region = $region_settings[$name] ?? []) {
          $label = $region['label'] ?? '';
          if (is_array($variables['region_attributes'])) {
            $variables['region_attributes'][$name]['title'] = $label;
          }
        }

        // Merge attributes taken from regions generated by Grid class.
        if ($region = $regions[$name] ?? []) {
          if ($attrs = $region['#attributes'] ?? []) {
            if (isset($variables['region_attributes'][$name])) {
              $variables['region_attributes'][$name]->merge(new Attribute($attrs));
            }
          }
          if ($cattrs = $region['#content_attributes'] ?? []) {
            if (isset($variables['region_content_attributes'][$name])) {
              $variables['region_content_attributes'][$name]->merge(new Attribute($cattrs));
            }
          }
        }
      }

      $regions = array_diff(array_keys($settings['regions']), ['bg']);
      $variables['regions'] = $regions;
    }
  }

  /**
   * Overrides variables for block.html.twig templates.
   *
   * {@inheritdoc}   */
  public static function preprocessBlock(array &$variables) {
    if ($settings = $variables['elements']['#blazy'] ?? []) {
      $variables['blazies'] = $settings['blazies']->storage();
    }
  }

  /**
   * Overrides variables for field.html.twig templates.
   *
   * {@inheritdoc}   */
  public static function preprocessField(array &$variables) {
    $element = &$variables['element'];
    $formatter = $element['#formatter'] ?? 'null';
    $blazy = strpos($formatter, 'blazy') !== FALSE;

    if ($blazy || isset($element['#blazy'])
    || !empty($element['#third_party_settings']['blazy']['blazy'])) {
      if ($settings = $element['#blazy'] ?? []) {
        /** @var \Drupal\blazy\BlazySettings $blazies */
        $blazies = $settings['blazies'];

        // @fixme might be 0 even has one if embedded inside LB blocks.
        if ($blazies->total() == 0) {
          $items = $variables['items'] ?? [];
          if ($items && !empty($items[0]['content'])) {
            $count = count($items);
            $settings['count'] = $count;
            $blazies->set('count', $count)
              ->set('total', $count);
          }
        }

        $variables['blazies'] = $blazies->storage();

        // Make Blazy background have less divities if just a single image.
        // Basically reverting to stable9 logic with minimal divities.
        if ($blazies->get('count') == 1) {
          $variables['multiple'] = FALSE;
          if (!empty($settings['background'])) {
            $variables['label_hidden'] = TRUE;
          }
        }
      }
    }
  }

  /**
   * Implements hook_theme_suggestions_alter().
   *
   * {@inheritdoc}   */
  public static function themeSuggestionsAlter(array &$suggestions, array $variables, $hook) {
    /** @var array<string, mixed> $elements */
    $elements = $variables['elements'] ?? [];
    /** @var array<string, mixed> $content */
    $content = $variables['content'] ?? [];
    if ($hook == 'layout') {
      /** @var array<string, mixed> $settings */
      $settings = $content['#settings'] ?? [];
      if (!empty($settings['blazy_layout'])) {
        $suggestions[] = 'layout__blazy';
      }
    }
    else {
      // Make Blazy background less troublesome if just a single image.
      // Basically reverting to stable9 logic with minimal divities.
      $settings = [];
      if ($hook == 'field') {
        /** @var array<string, mixed> $element */
        $element = $variables['element'] ?? [];
        /** @var array<string, mixed> $settings */
        $settings = $element['#blazy'] ?? [];
        if (!empty($settings['use_theme_field'])) {
          $settings = [];
        }
      }
      elseif ($hook == 'block') {
        /** @var array<string, mixed> $content */
        $content = $elements['content'] ?? [];
        $first_item = $content[0] ?? [];

        /** @var array<string, mixed> $settings */
        $settings = $first_item['#blazy'] ?? [];
      }

      if ($settings) {
        if (!empty($settings['use_lb'])
        && $blazies = $settings['blazies'] ?? NULL) {
          if ($blazies->use('bg') || $blazies->count() == 1) {
            $suggestions[] = $hook . '__blazy';
          }
        }
      }
    }
  }

  /**
   * Cleanup unused regions.
   *
   * @param array<string, mixed> $variables
   *   The variables being modified.
   * @param int $count
   *   The amount of regions.   .*/
  private static function cleanupRegions(array &$variables, int $count) {
    /** @var array<string, mixed> $settings */
    $settings = &$variables['settings'];
    $content = &$variables['content'];
    $bg = $content['bg'] ?? [];

    unset($content['bg']);

    foreach (Element::children($content) as $delta => $name) {
      if ($delta >= $count) {
        unset($content[$name]);
      }
    }

    if (empty($settings['remove_bg'])) {
      $content['bg'] = $bg;
    }
  }

  /**
   * Cleanup unwanted block attributes from builtin Media background.
   *
   * @param array<string, mixed> $variables
   *   The variables being modified.
   * @param string $name
   *   The name of region.   .*/
  private static function cleanupBlockAttributes(array &$variables, string $name) {
    /** @var array<string, mixed> $contents */
    $contents = &$variables['content'];
    if (isset($contents[$name])) {
      $subcontents = &$contents[$name];
      foreach ($subcontents as $uuid => &$content) {
        if (strpos($uuid, '-media') !== FALSE) {
          unset(
          $content['#attributes']['data-layout-block-uuid'],
          $content['#attributes']['data-layout-builder-highlight-id']
          );

          if ($classes = $content['#attributes']['class'] ?? []) {
            $classes = array_diff($classes, [
              'js-layout-builder-block',
              'layout-builder-block',
            ]);
            $content['#attributes']['class'] = $classes;
          }
          break;
        }
      }
    }
  }

  /**
   * Provides regions attributes.
   *
   * @param array<string, mixed> $variables
   *   The variables being modified.
   * @param string $name
   *   The name of region.   .*/
  private static function regionAttributes(array &$variables, string $name) {
    foreach (['attributes', 'content_attributes'] as $key) {
      if (!isset($variables["region_$key"][$name])) {
        if (!isset($variables['content'][$name]["#$key"])) {
          $variables['content'][$name]["#$key"] = [];
        }
        $variables["region_$key"][$name] = new Attribute($variables['content'][$name]["#$key"]);
      }
    }
  }

}
