<?php

/**
 * @file
 * Provides basic bLazy integration for lazy loading and multi-serving images.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\blazy\Blazy;

/**
 * Implements hook_theme().
 */
function blazy_theme() {
  return ['blazy' => ['render element' => 'element']];
}

/**
 * Prepares variables for blazy.html.twig templates.
 */
function template_preprocess_blazy(&$variables) {
  Blazy::buildAttributes($variables);
}

/**
 * Overrides variables for a responsive image.
 */
function blazy_preprocess_responsive_image(&$variables) {
  Blazy::buildResponsiveImageAttributes($variables);
}

/**
 * Implements hook_preprocess_field().
 */
function blazy_preprocess_field(array &$variables) {
  Blazy::buildWrapperAttributes($variables);
}

/**
 * Implements hook_config_schema_info_alter().
 */
function blazy_config_schema_info_alter(array &$definitions) {
  Blazy::configSchemaInfoAlter($definitions);
}

/**
 * Implements hook_help().
 */
function blazy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.blazy':
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}
