<?php

/**
 * @file
 * Provides a single, yet dynamic, Blazy layout for Layout Builder.
 */

use Drupal\blazy_layout\BlazyLayout;
use Drupal\blazy_layout\BlazyLayoutDefault;
use Drupal\Core\Template\Attribute;

/**
 * Provides a convenient shortcut for procedural hooks.
 *
 * @return \Drupal\blazy_layout\BlazyLayout
 *   The BlazyLayout manager class instance.
 */
// @codingStandardsIgnoreStart
function blazy_layout(): BlazyLayout {
  static $manager;

  if (!isset($manager)) {
    $manager = \Drupal::service('blazy_layout');
  }

  return $manager;
}
// @codingStandardsIgnoreEnd

/**
 * Implements hook_theme().
 */
function blazy_layout_theme() {
  return [
    'block__blazy' => [
      'base hook' => 'block',
    ],
    'field__blazy' => [
      'base hook' => 'field',
    ],
    'layout__blazy' => [
      'base hook' => 'layout',
    ],
  ];
}

/**
 * Overrides variables for layout.html.twig templates.
 */
function blazy_layout_preprocess_layout(&$variables) {
  $settings = &$variables['settings'];
  $namespace = $variables['content']['#namespace'] ?? NULL;

  if ($namespace == 'blazy') {
    if ($regions = $variables['content']['#regions'] ?? []) {
      $count = $settings['count'] = (int) $settings['count'];

      // Create an attributes variable for each region.
      foreach (range(1, $count) as $delta => $value) {
        $name = BlazyLayoutDefault::regionId($delta);
        // Attempts to make LB supports draggable with inner divs.
        // $lb_attrs = $variables['content'][$name]['#attributes'] ?? [];
        // If (isset($variables['content'][$name]['#attributes'])) {
        // if ($variables['content'][$name]['#attributes'] == $lb_attrs) {
        // $variables['content'][$name]['#attributes'] = [];
        // }
        // }
        // Core region attributes depend on content[region], hence enforced.
        foreach (['attributes', 'content_attributes'] as $key) {
          if (!isset($variables["region_$key"][$name])) {
            if (!isset($variables['content'][$name]["#$key"])) {
              $variables['content'][$name]["#$key"] = [];
            }
            $variables["region_$key"][$name] = new Attribute($variables['content'][$name]["#$key"]);
          }
        }

        // If ($variables['region_attributes'][$name]->toArray() == $lb_attrs) {
        // $variables['region_attributes'][$name] = new Attribute();
        // }
        // Merge attributes.
        if ($region = $regions[$name] ?? []) {
          if ($attrs = $region['#attributes'] ?? []) {
            $variables['region_attributes'][$name]->merge(new Attribute($attrs));
          }
        }

        // If ($lb_attrs) {
        // $variables['region_content_attributes'][$name]
        // ->merge(new Attribute($lb_attrs));
        // }
      }
    }
  }
}

/**
 * Overrides variables for block.html.twig templates.
 */
function blazy_layout_preprocess_block(&$variables) {
  $elements = &$variables['elements'];
  if ($settings = $variables['content'][0]['#blazy'] ?? []) {
    $blazies = $settings['blazies'];
    $variables['blazies'] = $blazies->storage();
  }
}

/**
 * Overrides variables for field.html.twig templates.
 */
function blazy_layout_preprocess_field(&$variables) {
  $element = &$variables['element'];
  $formatter = $element['#formatter'] ?? 'null';
  $blazy = strpos($formatter, 'blazy') !== FALSE;

  if ($blazy || isset($element['#blazy'])
    || !empty($element['#third_party_settings']['blazy']['blazy'])) {
      if ($settings = $element['#blazy'] ?? []) {
        $blazies = $settings['blazies'];
        $variables['blazies'] = $blazies;

        // @fixme might be 0 even has one if embedded inside LB blocks.
        if ($blazies->total() == 0) {
          $items = $variables['items'] ?? [];
          if ($content = $items[0]['content']) {
            $count = count($items);
            $settings['count'] = $count;
            $blazies->set('count', $count)
              ->set('total', $count);
          }
        }

        // Make Blazy background have less divities if just a single image.
        // Basically reverting to stable9 logic with minimal divities.
        if ($blazies->get('count') == 1) {
          $variables['multiple'] = FALSE;
          if (!empty($settings['background'])) {
            $variables['label_hidden'] = TRUE;
          }
        }

        /*
        if (!empty($settings['background'])) {
          $admin_uri = $settings['admin_uri'] ?? 'x';
          if (strpos($admin_uri, '/layout_builder/') !== FALSE) {

          }
        }
        */
      }
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function blazy_layout_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'layout') {
    $settings = $variables['content']['#settings'] ?? [];
    if (!empty($settings['blazy_layout'])) {
      $suggestions[] = 'layout__blazy';
    }
  }
  else {
    // Make Blazy background less troublesome if just a single image.
    // Basically reverting to stable9 logic with minimal divities.
    $settings = [];
    if ($hook == 'field') {
      $settings = $variables['element']['#blazy'] ?? [];
    }
    elseif ($hook == 'block') {
      $settings = $variables['elements']['content'][0]['#blazy'] ?? [];
    }

    if ($settings) {
      if (!empty($settings['use_lb']) && empty($settings['use_theme_field'])) {
        $blazies = $settings['blazies'];
        if ($blazies->use('bg') || $blazies->count() == 1) {
          $suggestions[] = $hook . '__blazy';
        }
      }
    }
  }
}

/**
 * Implements hook_help().
 */
function blazy_layout_help($route_name) {
  if ($route_name == 'help.page.blazy_layout') {
    $output = file_get_contents(dirname(__FILE__) . '/README.md');
    return blazy()->markdown($output);
  }
  return '';
}
